### ISSUE TITLE
Doesn't work with default VS Code dark theme

### ISSUE THREAD

**Issue by kevinkuebler** [blake-mealey/vscode-generate-wt-scheme#1]
Thanks for creating this extension, it's a great idea! Just installed it and discovered that it doesn't quite work with the default VS Code dark theme (i.e. "Dark+"). When you run the Generate Windows Terminal Scheme command with VS Code set to Dark+, you only get the name, foreground, and background properties generated, as seen here:
```
{
  "name": "VSCode",
  "background": "#1e1e1e",
  "foreground": "#d4d4d4"
}
```
It does seem to work with other VS Code themes.

**Comment by blake-mealey** [comment]
Interesting. I suspected this would be the case for some themes as the conversion works by translating the `terminal.ansiColor` fields, which I could see some themes skipping.

In this case I'd expect WT to look the same as the integrated terminal in VSCode. Can you confirm that?

I'd have to look into some other conversion process for themes that don't provide the terminal specific colors which would use some kind of heuristic to decide which colors to map to the ANSI colors.

I don't think I'll be taking the time to try that at the moment so if you wanted to look into it I would appreciate it.

Thanks

**Comment by kevinkuebler** [comment]
So it looks like it is actually missing a bunch of colors. When I apply that scheme in the terminal settings this is what it looks like.
![image](https://user-images.githubusercontent.com/95889/83640518-3ad74100-a57a-11ea-86dc-9f60666a7193.png)
Note that I'm using oh-my-posh and the PL version of Cascadia Code. So that could be part of the problem, but I think it's really just the missing colors. Note that even the `cd` command is black. Here it is in the VS Code integrated terminal.
![image](https://user-images.githubusercontent.com/95889/83640657-73771a80-a57a-11ea-99dc-0a4c99aa4ad0.png)
Not sure if I'll have time to dig into either, but if I do I'll let you know. Thanks!

**Comment by blake-mealey** [comment]
Hmm ok, thanks for the update. I might look into this a bit today since there seems to be more missing than in thought.

**Comment by blake-mealey** [comment]
Actually one other request. Could you send me a screenshot of what your terminal looks like in raw PowerShell 7?

**Comment by blake-mealey** [comment]
It turns out Dark+ uses the default theme colors for its terminal, and there is a way to access them. I have published a new version of the extension which fixes this.

**Comment by kevinkuebler** [comment]
Yep, new version works great now. Thanks again, this was a cool idea!
