### ISSUE TITLE
Configuration: Three Not Allowed Properties

### ISSUE THREAD

**Issue by devcrev** [blake-mealey/vscode-generate-wt-scheme#26]
These three properties, among the rest, were exported. The VS code editor I use for the WT json config reports them as "not allowed" properties:

```           
            "dropBackground": "#2677cb",
            "findMatchBackground": "#a8ac94",
            "findMatchHighlightBackground": "#ea5c00",
``` 

Note that all seems to be working fine in WT despite these warnings.

Note the top of my json file is:
```
    "$help": "https://aka.ms/terminal-documentation",
    "$schema": "https://aka.ms/terminal-profiles-schema",
```

**Comment by blake-mealey** [comment]
Thanks for the report. Fixed in latest version (0.0.6)
