### ISSUE TITLE
Two more not allowed properties

### ISSUE THREAD

**Issue by sphars** [blake-mealey/vscode-generate-wt-scheme#27]
Similar to #26, two more properties are generated but not allowed by the schema. These two are not allowed:

```
"hoverHighlightBackground": "#264f78",
"inactiveSelectionBackground": "#60daff",
```

Schema is still defined at [https://aka.ms/terminal-profiles-schema](https://aka.ms/terminal-profiles-schema)

Terminal v1.16.10261.0

**Comment by blake-mealey** [comment]
Thanks for the report! Should be fixed in v0.0.7. I switched to an include-list so this sort of bug shouldn't occur again.
