### ISSUE TITLE
Request for Permission to Use Your Code

### ISSUE THREAD

**Issue by RichardLuo0** [blake-mealey/vscode-generate-wt-scheme#28]
hi blake,
I would like to use part of your code in my project https://github.com/RichardLuo0/vscode-frosted-glass-theme
Please let me know if you have any specific terms or conditions for using your code.
Thank you for your time, and I look forward to your response.

**Comment by blake-mealey** [comment]
Hey thanks for asking first! No restrictions, use as you like
